DROP DATABASE IF EXISTS ladrillera;

CREATE DATABASE IF NOT EXISTS ladrillera;

USE ladrillera;

CREATE TABLE EMPLEADOS (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(250),
    apellido VARCHAR(250),
    cedula_ciudadania INT(11) UNSIGNED,
    genero VARCHAR(20),
    fecha_nacimiento DATE,
    rol VARCHAR(250),
    PRIMARY KEY (id)
);

CREATE TABLE USUARIOS (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    id_empleado INT(11) UNSIGNED NULL,
    nombre VARCHAR(250),
    contraseña VARCHAR(250),
    email VARCHAR(250),
    PRIMARY KEY (id),
    FOREIGN KEY (id_empleado) REFERENCES EMPLEADOS(id) ON DELETE CASCADE
);

CREATE TABLE CLIENTES (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(250),
    apellido VARCHAR(250),
    cedula_ciudadania INT(15) UNSIGNED,
    tipo_cliente VARCHAR(100),
    PRIMARY KEY (id)
);

CREATE TABLE PEDIDOS (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    id_cliente INT(11) UNSIGNED NOT NULL,
    PEDIDO VARCHAR(500),
    cantidad INT(15) UNSIGNED,
    descripcion TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id) ON DELETE CASCADE
);

CREATE TABLE PRODUCTOS (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(200),
    descripcion TEXT,
    imagen VARCHAR(200),
    PRIMARY KEY (id)
);

CREATE TABLE PRODUCTOS_PEDIDOS (
    id_pedido INT(11) UNSIGNED NOT NULL,
    id_producto INT(11) UNSIGNED NOT NULL,
    FOREIGN KEY (id_pedido) REFERENCES PEDIDOS(id) ON DELETE CASCADE,
    FOREIGN KEY (id_producto) REFERENCES PRODUCTOS(id) ON DELETE CASCADE
);

CREATE TABLE MODULO (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(200),
    PRIMARY KEY (id)
);

CREATE TABLE EMPLEADO_MODULO (
    id INT(11) UNSIGNED NOT NULL,
    id_empleado INT(11) UNSIGNED NOT NULL,
    FOREIGN KEY (id) REFERENCES MODULO(id) ON DELETE CASCADE,
    FOREIGN KEY (id_empleado) REFERENCES EMPLEADOS(id) ON DELETE CASCADE
);

CREATE TABLE VALIDACIONES (
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    id_empleado INT(11) UNSIGNED NOT NULL,
    id_pedido INT(11) UNSIGNED NOT NULL,
    fase INT(3) UNSIGNED NOT NULL,
    anexo VARCHAR(400),
    descripcion TEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (id_empleado) REFERENCES EMPLEADOS(id) ON DELETE CASCADE,
    FOREIGN KEY (id_pedido) REFERENCES PEDIDOS(id) ON DELETE CASCADE
);

CREATE TABLE EMPLEADOS_CLIENTES (
    id_cliente INT(11) UNSIGNED NOT NULL,
    id_empleado INT(11) UNSIGNED NOT NULL,
    FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id) ON DELETE CASCADE,
    FOREIGN KEY (id_empleado) REFERENCES EMPLEADOS(id) ON DELETE CASCADE
);

CREATE TABLE DOCUMENTOS(
    id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    id_cliente INT(11) UNSIGNED NOT NULL,
    nombre VARCHAR(250),
    descripcion TEXT,
    tipo_archivo VARCHAR(250),
    PRIMARY key (id),
    FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id) ON DELETE CASCADE
);